version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file: .env
    depends_on:
      - redis
    networks:
      - bot_network

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    env_file: .env
    command: celery -A app.workers.celery_app worker --loglevel=info --pool=solo
    depends_on:
      - redis
    networks:
      - bot_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
